### ISSUE TITLE
Support holidays

### ISSUE THREAD

**Issue by fnogatz** [cmichi/ulm-opening-hours#2]
Don't know where to get the dates from, but it would be very nice if the project would support holidays, both Germany-wide and regional (BaWü & BAY). Currently the normal Friday opening hours are displayed on Good Friday (Karfreitag, 29.03.2013).

I'm not sure how this should be handled as not every shop will be open like on Sunday, but this may be a good basis.

**Comment by ypid** [comment]
Any progress? Have you looked at #4 yet?
