### ISSUE TITLE
Map on website stays grey

### ISSUE THREAD

**Issue by KristjanESPERANTO** [cmichi/ulm-opening-hours#7]
Seems that the tiles can't be loaded: `Failed to load resource: the server responded with a status of 410 (Gone)`.

**Comment by cmichi** [comment]
Thanks for creating an issue!

The requests returned this body:

```
{"message":"Classic styles are no longer supported; see https://blog.mapbox.com/deprecating-studio-classic-styles-d8892ac38cb4 for more information"}
```

I've migrated to another style now [in this commit](https://github.com/cmichi/ulm-opening-hours/commit/65a02e121b011b0dcdb40b2de85370639c3d642f).
